storage:
  dbPath: "/mnt/c/Users/Augustin Pasquier/Documents/Cours/IUT/BUT INFO 2/R4.03 - Qualité et non relationnel/Projet/MongoData"
  journal:
    enabled: true
  wiredTiger:
    engineConfig:
      cacheSizeGB: 1
      directoryForIndexes: false
replication:
  replSetName: myReplicaSet
net:
  bindIp: 127.0.0.1
  port: 27017
